#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running pre-commit hook..."

# Check Prettier
pnpm run check:format || (
  echo "Prettier check failed. Please run 'yarn fix:format' to fix. ❌"
  false;
)

echo "Prettier check completed successfully. ✅ "

# Check ESLint
pnpm run check:lint || (
  echo "ESLint check failed. Please run 'yarn fix:lint' to fix. ❌ "
  false;
)

echo "ESLint check completed successfully. ✅ "

# Check Build
pnpm run build || (
  echo "Build failed ❌ "
  false;
)

echo "Build completed successfully. ✅ "

# Everything is good!
echo "Done. 🎉 "